apiVersion: v1
kind: Service
metadata:
  name: admin-ui
  namespace: auth-system
spec:
  type: NodePort
  selector:
    app: admin-ui
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
