apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: auth-system
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: mongoadmin
  MONGO_INITDB_ROOT_PASSWORD: StrongPassword123
