apiVersion: v1
kind: Secret
metadata:
  name: authapp-secrets
  namespace: auth-system
type: Opaque
stringData:
  # MongoDB connection
  MONGODB_URI: mongodb://authUser:StrongPassword123@34.234.94.21:27017/authDB?authSource=admin

  # Email configuration
  EMAIL_USER: avishkarlakade@gmail.com
  EMAIL_PASSWORD: lbrwmvzldsdcrntu

  # JWT configuration
  JWT_SECRET: 3398cc60e51a425fe7e68a690b1ca3a46b359131a1db1107fdb3683e97bfd63a
  JWT_REFRESH_SECRET: 20706c01f7c1a6dc3591cfbeb5b2ab98efa15a5f6d8414894997eeec9bbd3355
  JWT_EXPIRE: 7d
  JWT_REFRESH_EXPIRE: 30d

  # Session secret
  SESSION_SECRET: fe830c894f5bff1a4a6c11269578792c95a27a3341879e94e4abfecfa7fce1

  # reCAPTCHA
  RECAPTCHA_SECRET_KEY: 6LclnvQrAAAAADOliQVPum_zKCSYRKk2lQQjlC4Q

  # Google OAuth
  GOOGLE_CLIENT_ID: 33699832281-onsre8eojf9pu3gnphcvaod9iiu9bj69.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 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
  GOOGLE_CALLBACK_URL: http://34.234.94.21:5001/api/auth/google/callback

  # Admin credentials
  ADMIN_EMAIL: admin@yourdomain.com
  ADMIN_PASSWORD: secureAdminPassword123!

  # Frontend URL
  FRONTEND_URL: http://34.234.94.21:8080
