apiVersion: v1
kind: Secret
metadata:
  name: authapp-secrets
  namespace: auth-system
type: Opaque
stringData:
  # Email configuration
  EMAIL_USER: avishkarlakade@gmail.com
  EMAIL_PASSWORD: lbrwmvzldsdcrntu

  # MongoDB
  MONGODB_URI: mongodb://authUser:StrongPassword123@<EC2_PUBLIC_IP>:27017/authDB

  # JWT configuration
  JWT_SECRET: your_jwt_secret
  JWT_REFRESH_SECRET: your_jwt_refresh_secret
  JWT_EXPIRE: 7d
  JWT_REFRESH_EXPIRE: 30d

  # reCAPTCHA
  RECAPTCHA_SECRET_KEY: 6LclnvQrAAAAADOliQVPum_zKCSYRKk2lQQjlC4Q

  # Google OAuth
  GOOGLE_CLIENT_ID: 33699832281-onsre8eojf9pu3gnphcvaod9iiu9bj69.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 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
  GOOGLE_CALLBACK_URL: http://<EC2_PUBLIC_IP>:5000/api/auth/google/callback

  # Session
  SESSION_SECRET: your_session_secret

  # Admin credentials
  ADMIN_EMAIL: admin@yourdomain.com
  ADMIN_PASSWORD: secureAdminPassword123!

  # Frontend URL
  FRONTEND_URL: http://<EC2_PUBLIC_IP>:8080
